# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_serverlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='opera',
            field=models.SmallIntegerField(choices=[(0, '管理'), (1, '远程链接'), (2, '续费'), (3, '升级'), (4, '更多')], default=0, verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='config',
            field=models.CharField(max_length=50, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='name',
            field=models.CharField(max_length=20, verbose_name='设备名称'),
        ),
    ]
